# Generated by Django 3.0.5 on 2022-07-30 03:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profileimg', models.ImageField(default='uploads\\pic.jfif', upload_to='uploads')),
                ('organisation', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('yof', models.IntegerField(default=2001, validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(2000)])),
                ('LinkProfile', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
